### ISSUE TITLE
"dvara" set up for my mongoDB help needed i am begging for help

### ISSUE THREAD

**Issue by agwl-saurabh** [daaku/go.redis#4]
Sorry for posting here i am in deep trouble. and i don't have your email ID

I want your help in "dvara" set up for my mongoDB instance.  as per the git and google i can't find tutorial for dvara as this is not popular. can you please provide some steps to set up dvara on AWS (i am not able to run). i am new to go and my app is falling and not wokring at all. i am begging you for help as i am paying for server more then i am earning. 

 I am running Parse server open source for my app. and i have lot of request in mongo DB as my app is like instaragaram to lot of images video and Mongo DB request is making my app slow even my app is not wokring as its taking so much merory. I tried mongodb sharding but its not wokring for me and my app is not responding for almost all query.

Right now I am runing my mongo DB on R4.2xlarge server with replica set (as sharding not helpfull for me app). total cost of AWS i am paying more then 1200$ which i can't effort. 

Please please help i only have hope from you to help it will not take 10-15 min for you. please help !!!!!!!
Please provide your email ID 
My email ID is :- agwl.saurabh@outlook.com

**Comment by daaku** [comment]
Hey, sorry to hear you're not having success with dvara. As it says in the readme Facebook isn't using it anymore either. Additionally I no longer work there anymore either.

If your application is suffering from Mongo DB slowness then dvara isn't going to fix that. It simply serves as a connection pooling proxy. I would suggest trying to optimize your mongo use rather than try to use dvara to fix it.
